services:
  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  go:
    build: ./go
    container_name: go
    ports:
      - "8080:8080"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
